name: Android Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_TOOLS:    "4333796"
      ANDROID_SDK_ID:    "system-images;android-28;google_apis;x86_64"
      EMULATOR_NAME:    "emulator"

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: BuildCapacitorPlugin(This plugin itself)
        run: |
          npm install
          npm run build

      - name: Insatall Quasar
        run: cd demo && yarn install

      - name: Build with Quasar
        run: cd demo && npx quasar build --mode capacitor --target android

      - name: Install Android sdkmanager
        run: |
          sudo mkdir -p /root/.android && sudo touch /root/.android/repositories.cfg
          wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip
          sudo unzip -d $ANDROID_HOME android-sdk.zip > /dev/null

      - name: Install Android image
        run: |
          echo "y" | sudo $ANDROID_HOME/tools/bin/sdkmanager --install ${ANDROID_SDK_ID}

#      - name: Start AVD
#        run: |
#          # create avd -n tempolary_emulator_name -k sdk_id
#          echo "no" | sudo $ANDROID_HOME/tools/bin/avdmanager create avd -n ${EMULATOR_NAME} -k ${ANDROID_SDK_ID} --force
#          sudo $ANDROID_HOME/emulator/emulator -list-avds
#          echo "Starting emulator"
#          sudo nohup $ANDROID_HOME/emulator/emulator -avd ${EMULATOR_NAME} -no-snapshot > /dev/null 2>&1 &
#          sudo $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'
#          sudo $ANDROID_HOME/platform-tools/adb devices
#          echo "Emulator started"

#      - name: Set up Appium
#        run: npm install appium@1.15.0
#
#      - name: Run Appium Server
#        run: ./node_modules/.bin/appium --log-timestamp --log-no-colors --allow-insecure chromedriver_autodownload > appium.log &
#
#      - name: Build with Gradle
#        run: cd demo/src-capacitor/android/ && gradle compileJava
#        continue-on-error: true

#      - name: Upload logs
#        uses: actions/upload-artifact@v1
#        with:
#          name: appium.log
#          path: appium.log
#
#      - name: Upload screenshots
#        uses: actions/upload-artifact@v1
#        with:
#          name: screenshots
#          path: screenshots
